cargo run --example chain_failure
cargo run --example chain_failure_delay_retries
cargo run --example chain_retries_delay_cleanup
cargo run --example despawn_on_completion
cargo run --example error
cargo run --example input
cargo run --example kill
cargo run --example retries_and_delay_and_cleanup
cargo run --example retries_and_delay
cargo run --example retries_and_remove
cargo run --example simple
cargo run --example simple_chain